version: '3.8'

services:
  app: # for developing
    image: ubuntu:latest
    container_name: spring_app
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - db
      - redis
    command: tail -f /dev/null

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind, ro
      device: "${PWD}/postgres_data"
